config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  resource :user, except: [:new, :create, :destroy]
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true  
  
  has_many :recipes, dependent: :destroy  
  has_many :favorites, dependent: :destroy 
  
  def already_favorited?(recipe)
    self.favorites.exists?(recipe_id: recipe.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path
  end

  def after_sign_up_path_for(resource)
    user_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
  def create
    @favorite = current_user.favorite.create(recipe_id: params[:recipe_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorite.find_by(recipe_id: @recipe.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: '投稿に成功しました' 
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user_id != current_user.id
      redirect_to recipes_path, alert: '不正なアクセスです'
    end
  end

  def update
    @recipe  = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: '更新に成功しました'
    else
      render :edit  
    end  
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報を更新しました'
    else
      render :edit
    end  
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavariteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8a6f533382.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'recipegram', root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'マイページ', user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規投稿', new_recipe_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to '投稿一覧', recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>  

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/recipes/_error.html.erb
<% if @recipe.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@recipe.errors.count, "error") %></h4>
    <p><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for recipe do |f| %>
  <div class="form-group">
    <label>レシピ名</label>
    <%= f.text_field :title, class: 'form-control' %>
  <div>  
  <div class="form-group">
    <label> 作り方</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>  
  <div>
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'error', recipe: @recipe%>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= render 'form', recipe: @recipe %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">レシピ名</th>
            <th scope="col">投稿者</th>
            <th scope="col">　</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td><%= link_to recipe.title, recipe_path(recipe) %></td>
              <td><%= recipe.user.name %></td>
              <td>
                <% if current_user.already_favorited?(recipe) %>
                  <%= link_to recipe_favorites_path(recipe), method: :delete do %>
                   <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to recipe_favorites_path(recipe), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
                <%= recipe.favorites.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'error', recipe: @recipe%>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
      <%= render 'form', recipe: @recipe%>
    </div>
  </div>
</div>      

app/views/recipes/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @recipe.title %></h5>
          <p class="card-text"><%= simple_format @recipe.body %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @recipe.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
           <% if current_user.already_favorited?(@recipe) %>
            <%= link_to recipe_favorites_path(@recipe), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
            <%= @recipe.favorites.count %>
          <% else %>
            <%= link_to recipe_favorites_path(@recipe), method: :post do %>
              <i class="far fa-heart"></i>
            <% end %>
            <%= @recipe.favorites.count %>
          <% end %>
          <% if @recipe.user == current_user %>
            <%= link_to '編集', edit_recipe_path(@recipe), class: "btn btn-success" %>
            <%= link_to '削除', recipe_path(@recipe), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>ユーザー名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= current_user.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
          <%= link_to 'ユーザー編集', edit_user_path %>
        <div>
      </div>
    </div>
  </div> 
</div>       